sample/demo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ratio$', views.aspect_ration_renditions, name='ratio'),
    url(r'^random$', views.random_renditions, name='random'),
    url(r'^filters$', views.filters, name='filters'),
]

sample/sample/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('demo.urls', namespace='demo')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^renderer/', include('renderer.urls', namespace='renderer')),
]

if settings.AWS_SECRET_ACCESS_KEY is None:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

admin.site.site_header = 'Image Renderer Sample'

sample/demo/models.py
from django.db import models

# Create your models here.
class DemoModel(models.Model):
    master = models.ForeignKey('renderer.MasterImage')

sample/demo/views.py
import markdown2
import codecs
import os

from random import randint
from django.conf import settings
from django.shortcuts import render
from renderer.models import MasterImage


def index(request):
    m = MasterImage.objects.first()
    readme_path = os.path.join(settings.BASE_DIR, '..', 'README.md')
    input_file = codecs.open(readme_path, mode='r', encoding='utf-8')
    text = input_file.read()
    text = text.split('## Sample project', 1)[0]
    html = markdown2.markdown(text, extras=['fenced-code-blocks', ])
    return render(request, 'demo/index.html', {
        'text': html,
    })


def aspect_ration_renditions(request):
    m = MasterImage.objects.first()
    renditions = []
    for i in range(0, 4):
        renditions.append((
            randint(0, min(m.master_width, 768/2)),
            0,
        ))
    for i in range(0, 4):
        renditions.append((
            0,
            randint(0, m.master_height),
        ))
    return render(request, 'demo/ratio.html', {
        'master': m,
        'renditions': renditions,
    })


def random_renditions(request):
    m = MasterImage.objects.first()
    renditions = []
    for i in range(0, 8):
        renditions.append((
            randint(0, min(m.master_width, 768/2)),
            randint(0, m.master_height),
        ))
    return render(request, 'demo/random.html', {
        'master': m,
        'renditions': renditions,
    })


def filters(request):
    m = MasterImage.objects.first()
    return render(request, 'demo/index.html', {
        'master': m,
        'renditions': [],
    })

sample/demo/templates/demo/base.html
{% load i18n %}
<!doctype html>
<html lang="">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-1.11.3.min.js" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
		<title>Django Image Renderer Sample</title>
		<style>
		* {
			border-radius: 0 !important;
		}
		body {
			padding-top: 70px;
		}
		.navbar {
			border: none !important;
		}
		footer {
			text-align: center;
			color: #767676;
			font-size: 0.8em;
			margin: 20px;
		}
		.master {
			text-align: center;
		}
		.rendition {
			overflow: hidden;
			margin: 5px;
			background-color: #eee;
			text-align: center;
			padding-top: 10px;
		}
		.rendered-image {
			margin: 10px 0;
		}
		.fork-me {
			position: fixed;
			top: 0;
			right: 0;
			border: 0;
			z-index: 9999;
		}
		</style>
		{% block head %}
		{% endblock %}
	</head>
	<body>
		<!--[if lt IE 9]>
			<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'demo:index' %}">Django image renderer</a>
			</div>
			{% url 'demo:index' as index_url %}
			{% url 'demo:ratio' as ratio_url %}
			{% url 'demo:random' as random_url %}
			{% url 'demo:filters' as filters_url %}
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="{% if ratio_url == request.get_full_path %}active{% endif %}">
						<a href="{{ ratio_url }}">renditions {% if index_url == request.get_full_path %}<span class="sr-only">(current)</span>{% endif %}</a>
					</li>
					<li class="{% if random_url == request.get_full_path %}active{% endif %}">
						<a href="{{ random_url }}">random renditions {% if index_url == request.get_full_path %}<span class="sr-only">(current)</span>{% endif %}</a>
					</li>
					<!--<li class="{% if filters_url == request.get_full_path %}active{% endif %}">
						<a href="{{ filters_url }}">filters {% if filters_url == request.get_full_path %}<span class="sr-only">(current)</span>{% endif %}</a>
					</li>-->
					<li class="visible-xs-block">
						<a href="https://github.com/rouk1/django-image-renderer">Github project</a>
					</li>
				</ul>
			</div>
		</nav>
		<div class="container">
			{% block body %}
			{% endblock %}
		</div>
		<footer>this demo website is hosted courtesy of <a href="http://www.dvmobile.fr">DVMobile</a></footer>

		<a href="https://github.com/rouk1/django-image-renderer" class="fork-me hidden-xs">
			<img
				src="https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67"
				alt="Fork me on GitHub"
				data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png">
		</a>
		{% block script %}
		{% endblock %}
		<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-70142756-1', 'auto');
ga('send', 'pageview');
		</script>
	</body>
</html>

sample/demo/templates/demo/index.html
{% extends "demo/base.html" %}
{% load renderer %}

{% block head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js"></script>
{% endblock %}

{% block body %}
{{ text|safe }}
{% endblock %}

{% block script %}
<script>
$(document).ready(function() {
    $('pre code').each(function(i, block) {
        hljs.highlightBlock(block);
    });
});
</script>
{% endblock %}

sample/demo/templates/demo/random.html
{% extends "demo/renditions.html" %}
{% load renderer %}

{% block title %}
<h1>Random rendering samples</h1>
<p class="lead">this page generate {{ renditions|length }} random renditions of this master</p>
<p class="master">{% rendition master 0 0 %}</p>
{% endblock %}

sample/demo/templates/demo/ratio.html
{% extends "demo/renditions.html" %}
{% load renderer %}

{% block title %}
<h1>Aspect ratio rendering samples</h1>
<p class="lead">this page generates renditions that conserve aspect ratio of this master</p>
<p class="master">{% rendition master 0 0 %}</p>
{% endblock %}

sample/demo/templates/demo/renditions.html
{% extends "demo/base.html" %}
{% load renderer %}

{% block head %}
{% endblock %}

{% block body %}
<div class="jumbotron">
    {% block title %}
    {% endblock %}
</div>
<div class="row">
{% for w, h in renditions %}
    <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="rendition">
            <code class="template-tag">
                {% verbatim %}
                {% rendition master
                {% endverbatim %}
                {{ w }} {{ h }}
                {% verbatim %}%}{% endverbatim %}
            </code>
            <div class="rendered-image">
                {% rendition master w h %}
            </div>
        </div>
    </div>
{% if forloop.counter|divisibleby:2 %}
    </div>
    {% if not forloop.last %}
    <div class="row">
    {% endif %}
{% endif %}
{% endfor %}
<p>bender by <a href="http://se7enes.deviantart.com/">se7enes</a>
{% endblock %}

{% block script %}
{% endblock %}